name: PCF Solution Build

on:
  push:
    branches:
      - master  # Workflow execution will be triggered when code is pushed to the "main" branch

jobs:
  build:
    runs-on: windows-latest # ubuntu-latest  # Uses an Ubuntu runtime environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Downloads the source code

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Sets up the Node.js environment

      - name: Install Dependencies
        working-directory: ./src  # Sets the working directory to the control directory
        run: npm install  # Installs project dependencies for the PCF control

      - name: Build PCF Control
        working-directory: ./src  # Sets the working directory to the control directory
        run: npm run build  # Executes the build process for the PCF control

      - name: Build Solution
        working-directory: ./src/solution  # Sets the working directory to the solution directory
        run: npm install && npm run build  # Installs dependencies and executes the build process for the solution

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build and Package PCF Solution
        working-directory: ./src/solution  # Sets the working directory to the solution directory
        run: msbuild /t:build /restore

      - name: Archive Solution
        uses: actions/upload-artifact@v2
        with:
          name: solution
          path: ./src/solution  # Archives the solution directory

      # - name: Archive PCF Control
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: pcf-control
      #     path: ./src/control  # Archives the PCF control directory
